FROM public.ecr.aws/lambda/python:3.11
COPY ./requirements.txt ${LAMBDA_TASK_ROOT}

# install dependencies
RUN pip3 install --user -r ${LAMBDA_TASK_ROOT}/requirements.txt
# Copy function code and models into our /var/task
COPY ./model ${LAMBDA_TASK_ROOT}/model
COPY ./*.py ${LAMBDA_TASK_ROOT}

ENV TRANSFORMERS_CACHE /var/cache
# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "handler.handler" ]